# Generated by Django 4.2.30 on 2026-04-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='height_m',
        ),
        migrations.AddField(
            model_name='submission',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, default=170.0, max_digits=5, verbose_name='Height (cm)'),
        ),
    ]
